### ISSUE TITLE
After switch to static class, multiple calls to Lookup result in an error due to the initialization code

### ISSUE THREAD

**Issue by ben-m-lucas** [ujjwol/MimeSharp#8]
Using the following xUnit test:

```
    public class when_performing_multiple_mime_lookups
    {
        [Fact]
        public void supports_making_multiple_lookups()
        {
            var firstResult = Mime.Lookup("test.html");
            var secondResult = Mime.Lookup("test.pdf");

            firstResult.Should().NotBeNullOrEmpty();
            secondResult.Should().NotBeNullOrEmpty();
        }
    }
```

The following exception is thrown:

System.ArgumentException
An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MimeSharp.Mime.Init() in C:\Users\blucas\Source\Repos\MimeSharp\MimeSharp\Mime.cs:line 38
   at MimeSharp.Mime.Lookup(String filePath) in C:\Users\blucas\Source\Repos\MimeSharp\MimeSharp\Mime.cs:line 48
   at MimeSharp.Tests.when_performing_multiple_mime_lookups.supports_making_multiple_lookups() in C:\Users\blucas\Source\Repos\MimeSharp\MimeSharp.Tests\when_performing_multiple_mime_lookups.cs:line 13

**Comment by SteveK-GS** [comment]
Why not initialise in a static constructor?

**Comment by ben-m-lucas** [comment]
Excellent point.  By switching to a static constructor, I can get rid of the lock and synchronization code.  Definitely makes the class easier to read.
